### PR TITLE
Handle groups when adding users

### PR DESCRIPTION
**Pull request by ktsakalozos**
Adding users does not use primary group. Users are added to requested groups after creation.
Fix minor typo in docs.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
This PR includes a fix in the way we read the /etc/environment file. We need to strip it from the \n characters before we put its contents to the env dictionary. In this way the " character can be stripped from both the beginning and the end of the variables value.

**Comment by johnsca** [comment]
I got this error when testing with this change: http://pastebin.ubuntu.com/13506551/

This was after adding and removing the relation a couple of times, so it might be something of an edge case, but we need to make sure we handle it.

**Comment by johnsca** [comment]
Apparently this happens on initial install as well.  I think a better approach is to get this MP approved and released: https://code.launchpad.net/~johnsca/charm-helpers/adduser-group/+merge/278649

**Comment by johnsca** [comment]
The reason this happens on initial install is that the [dist.yaml](https://bazaar.launchpad.net/~bigdata-dev/charms/trusty/apache-hadoop-yarn-master/trunk/view/head:/dist.yaml) explicitly lists the `mapred` group, so it gets explicitly created before the `mapred` user.  For this change to work, we would have to remove the explicit `mapred` group from the `dist.yaml` (for each charm), but we'd still be left with a different primary group (`mapred` instead of `hadoop`).

**Pull request closed without merging**
